### ISSUE TITLE
layout error

### ISSUE THREAD

**Issue by springlo** [arturdev/SwiftyCodeView#1]
`
"<NSLayoutConstraint:0x60c0002804b0 UIView:0x7fe60ee14920.height == 40   (active)>",
    "<NSLayoutConstraint:0x60c000280500 V:[UIView:0x7fe60ee14920]-(0)-|   (active, names: '|':SwiftyCodeView.SwiftyCodeItemView:0x7fe60ee14600 )>",
    "<NSLayoutConstraint:0x60c0002805f0 V:|-(0)-[UIView:0x7fe60ee14920]   (active, names: '|':SwiftyCodeView.SwiftyCodeItemView:0x7fe60ee14600 )>",
    "<NSLayoutConstraint:0x608000091440 'UISV-alignment' SwiftyCodeView.SwiftyCodeItemView:0x7fe60ee0fe70.bottom == SwiftyCodeView.SwiftyCodeItemView:0x7fe60ee14600.bottom   (active)>",
    "<NSLayoutConstraint:0x608000091710 'UISV-alignment' SwiftyCodeView.SwiftyCodeItemView:0x7fe60ee0fe70.top == SwiftyCodeView.SwiftyCodeItemView:0x7fe60ee14600.top   (active)>",
    "<NSLayoutConstraint:0x608000091210 'UISV-canvas-connection' UIStackView:0x7fe612506450.top == SwiftyCodeView.SwiftyCodeItemView:0x7fe60ee0fe70.top   (active)>",
    "<NSLayoutConstraint:0x608000091260 'UISV-canvas-connection' V:[SwiftyCodeView.SwiftyCodeItemView:0x7fe60ee0fe70]-(0)-|   (active, names: '|':UIStackView:0x7fe612506450 )>",
    "<NSLayoutConstraint:0x608000090540 'UIView-Encapsulated-Layout-Height' UIStackView:0x7fe612506450.height == 58   (active)>"
`

**Comment by arturdev** [comment]
Can you provide more details?

**Comment by springlo** [comment]
I have solved this problem， Thx。
