### ISSUE TITLE
Keyboard type of textfield is Fixed

### ISSUE THREAD

**Issue by EjazAppxone** [arturdev/SwiftyCodeView#2]
Can you add a property to change keyboard type from NumberPad to Default?

**Comment by arturdev** [comment]
Please take a look at the [demo](https://github.com/arturdev/SwiftyCodeView/tree/master/SwiftyCodeViewDemo/SwiftyCodeViewDemo) project. 
As you can see in your [CustomCodeItemView](https://github.com/arturdev/SwiftyCodeView/blob/master/SwiftyCodeViewDemo/SwiftyCodeViewDemo/CustomCodeView/CustomCodeViewItem.swift) class you have access to the textfield, so you're free to do anything you want with the textfield.

**Comment by EjazAppxone** [comment]
Thanks :)
