### ISSUE TITLE
is there a way to clear text manually?

### ISSUE THREAD

**Issue by shujavf** [arturdev/SwiftyCodeView#4]

**Comment by arturdev** [comment]
There is no way to clear text directly for now. 
As a quick solution, I would suggest the following:
```Swift
let items = codeView.subViews.compactMap({$0 as? UIStackView}).first?.arrangesSubviews.compactMap({$0 as? SwiftyCodeItemView})
items.forEarch({ $0.textField.text = "" })
```

**Comment by arturdev** [comment]
From now on you can clear text by just assigning an empty string to the `code` variable. 
`codeView.code = "" `
